# Generated by Django 5.2 on 2025-04-22 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiamiento_pagos', to='pagos.formaspagomodel', verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financiamiento_pago', to='pagos.transaccionesmodel', verbose_name='Transacción'),
        ),
    ]
