# Generated by Django 5.2.4 on 2025-07-04 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Eliminado Lógicamente')),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo de la Cita')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado de la Cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='paciente.pacientemodel', verbose_name='Paciente')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_actualizacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_creacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_cita'],
                'unique_together': {('paciente', 'fecha_cita')},
            },
        ),
    ]
