# Generated by Django 5.2.5 on 2025-08-31 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_usermodel_address_alter_usermodel_date_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyModel',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.auditmodel')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            bases=('core.auditmodel',),
        ),
        migrations.CreateModel(
            name='TreatmentsModel',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.auditmodel')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duración')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Especialista')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatments.specialtymodel', verbose_name='Especialidad')),
            ],
            bases=('core.auditmodel',),
        ),
    ]
