# Generated by Django 5.2.5 on 2025-08-31 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usermodel_address_alter_usermodel_date_birth_and_more'),
        ('odontogram', '0001_initial'),
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialtymodel',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='treatmentsmodel',
            options={'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.CreateModel(
            name='AppliedTreatmentsModel',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.auditmodel')),
                ('apply_date', models.DateField(auto_now_add=True, verbose_name='Fecha de aplicación')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio final')),
                ('status', models.CharField(choices=[('CD', 'Presupuestado'), ('PE', 'Pendiente'), ('AP', 'Aplicado'), ('CA', 'Cancelado')], default='PE', max_length=2, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('teeth', models.ManyToManyField(blank=True, to='odontogram.teethmodel', verbose_name='Dientes')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatments.treatmentsmodel', verbose_name='Tratamiento')),
            ],
            options={
                'verbose_name': 'Tratamiento aplicado',
                'verbose_name_plural': 'Tratamientos aplicados',
            },
            bases=('core.auditmodel',),
        ),
    ]
