# Generated by Django 5.2.5 on 2025-08-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_alter_specialtymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedtreatmentsmodel',
            name='apply_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de aplicación'),
        ),
    ]
