# Generated by Django 5.2.5 on 2025-08-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_alter_appliedtreatmentsmodel_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedtreatmentsmodel',
            name='apply_date',
            field=models.DateField(verbose_name='Fecha de aplicación'),
        ),
    ]
