# Generated by Django 5.2 on 2025-04-08 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(error_messages={'required': 'Este campo es obligatorio'}, help_text='Nombre del paciente', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(error_messages={'required': 'Este campo es obligatorio'}, help_text='Apellido del paciente', max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True, verbose_name='Fecha de nacimiento')),
                ('calle', models.CharField(blank=True, help_text='Calle del paciente', max_length=100, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, help_text='Número de la calle del paciente', max_length=10, null=True, verbose_name='Número')),
                ('colonia', models.CharField(blank=True, help_text='Colonia del paciente', max_length=100, null=True, verbose_name='Colonia')),
                ('cp', models.CharField(blank=True, help_text='Código postal del paciente', max_length=10, null=True, verbose_name='Código postal')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad del paciente', max_length=100, null=True, verbose_name='Ciudad')),
                ('estado', models.CharField(blank=True, help_text='Estado del paciente', max_length=100, null=True, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, help_text='País del paciente', max_length=100, null=True, verbose_name='País')),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, help_text='Límite de crédito del paciente', max_digits=10, null=True, verbose_name='Límite de crédito')),
                ('saldo_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo actual del paciente', max_digits=10, null=True, verbose_name='Saldo actual')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del paciente', max_length=15, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, help_text='Celular del paciente', max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, help_text='Email del paciente', max_length=100, null=True, verbose_name='Email')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
