# Generated by Django 5.2 on 2025-04-15 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedicoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('allergies', models.TextField(blank=True, help_text='Alergias del paciente', verbose_name='Alergias')),
                ('medical_conditions', models.TextField(blank=True, help_text='Condiciones médicas del paciente', verbose_name='Condiciones Médicas')),
                ('current_medications', models.TextField(blank=True, help_text='Medicamentos actuales del paciente', verbose_name='Medicamentos Actuales')),
                ('past_medications', models.TextField(blank=True, help_text='Medicamentos pasados del paciente', verbose_name='Medicamentos Pasados')),
                ('blood_type', models.CharField(blank=True, help_text='Tipo de sangre del paciente', max_length=5, verbose_name='Tipo de Sangre')),
                ('last_update', models.DateField(auto_now=True, help_text='Última actualización del historial médico', verbose_name='Última Actualización')),
                ('additional_notes', models.TextField(blank=True, help_text='Notas adicionales sobre el paciente', verbose_name='Notas Adicionales')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='paciente.pacientemodel', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
                'db_table': 'historiales_medicos',
            },
        ),
    ]
