# Generated by Django 5.2 on 2025-04-21 17:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleteraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre que agrupa a formas de pago', max_length=30, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la billetera', null=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
                'db_table': 'billeteras',
            },
        ),
        migrations.CreateModel(
            name='FormasPagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre de la forma de pago', max_length=30, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la forma de pago', null=True, verbose_name='Descripción')),
                ('balance', models.DecimalField(decimal_places=4, help_text='Dinero disponible en la forma de pago', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance')),
                ('catalogo_sat', models.CharField(blank=True, help_text='Código SAT de la forma de pago', max_length=10, null=True, verbose_name='Catalogo SAT')),
                ('billetera', models.ForeignKey(help_text='Billetera a la que pertenece la forma de pago', on_delete=django.db.models.deletion.PROTECT, related_name='formas_pago', to='pagos.billeteramodel', verbose_name='Billetera')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Formas de pago',
                'db_table': 'formas_pago',
            },
        ),
        migrations.CreateModel(
            name='TransaccionesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('fecha', models.DateField(help_text='Fecha de la transacción', verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=4, help_text='Monto de la transacción', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('concepto', models.CharField(help_text='Concepto de la transacción', max_length=100, verbose_name='Concepto')),
                ('tipo_movimiento', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('EPA', 'Entrada por ajuste'), ('SPA', 'Salida por ajuste')], help_text='Tipo de movimiento de la transacción', max_length=10, verbose_name='Tipo de movimiento')),
                ('referencia', models.CharField(blank=True, help_text='Referencia de la transacción', max_length=50, null=True, verbose_name='Referencia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('forma_pago', models.ForeignKey(help_text='Forma de pago de la transacción', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='pagos.formaspagomodel', verbose_name='Forma de pago')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transacciones',
            },
        ),
    ]
