# Generated by Django 5.2 on 2025-04-15 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('paciente', '0002_historialmedicopaciente'),
        ('tratamientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('general_observations', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='odontograms', to=settings.AUTH_USER_MODEL, verbose_name='Dentista')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograms', to='paciente.pacientemodel', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('number', models.PositiveSmallIntegerField(help_text='Según sistema de notación universal/FDI', unique=True, verbose_name='Número')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tooth_type', models.CharField(choices=[('incisor', 'Incisivo'), ('canine', 'Canino'), ('premolar', 'Premolar'), ('molar', 'Molar')], max_length=10, verbose_name='Tipo')),
                ('position', models.CharField(choices=[('upper_right', 'Superior Derecha'), ('upper_left', 'Superior Izquierda'), ('lower_right', 'Inferior Derecha'), ('lower_left', 'Inferior Izquierda')], max_length=15, verbose_name='Posición')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diente',
                'verbose_name_plural': 'Dientes',
                'db_table': 'dental_tooth',
                'unique_together': {('number', 'position')},
            },
        ),
        migrations.CreateModel(
            name='DentalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('xray', 'Radiografía'), ('panoramic', 'Panorámica'), ('photo', 'Fotografía'), ('consent', 'Consentimiento'), ('report', 'Informe'), ('other', 'Otro')], max_length=10, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='dental_documents/%Y/%m/', verbose_name='Archivo')),
                ('uploaded_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='citas.appointment', verbose_name='Cita')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_documents', to='paciente.pacientemodel', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('teeth', models.ManyToManyField(blank=True, related_name='documents', to='registros_dentales.tooth', verbose_name='Dientes Relacionados')),
            ],
            options={
                'verbose_name': 'Documento Dental',
                'verbose_name_plural': 'Documentos Dentales',
                'db_table': 'dental_document',
            },
        ),
        migrations.CreateModel(
            name='ToothStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('tooth_state', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('implant', 'Implante'), ('temporary', 'Temporal'), ('to_extract', 'Para Extraer')], default='present', max_length=15, verbose_name='Estado del diente')),
                ('recorded_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='tooth_status_records', to=settings.AUTH_USER_MODEL, verbose_name='Dentista')),
                ('odontogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_status', to='registros_dentales.odontogram', verbose_name='Odontograma')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_records', to='registros_dentales.tooth', verbose_name='Diente')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Diente',
                'verbose_name_plural': 'Estados de Dientes',
                'db_table': 'dental_tooth_status',
                'unique_together': {('odontogram', 'tooth')},
            },
        ),
        migrations.CreateModel(
            name='ToothSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('surface', models.CharField(choices=[('V', 'Vestibular'), ('L', 'Lingual/Palatino'), ('M', 'Mesial'), ('D', 'Distal'), ('O', 'Oclusal'), ('I', 'Incisal')], max_length=1, verbose_name='Superficie')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='registros_dentales.tooth', verbose_name='Diente')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Superficie Dental',
                'verbose_name_plural': 'Superficies Dentales',
                'db_table': 'dental_surface',
                'unique_together': {('tooth', 'surface')},
            },
        ),
        migrations.CreateModel(
            name='DentalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('condition_type', models.CharField(choices=[('caries', 'Caries'), ('restoration', 'Restauración'), ('crown', 'Corona'), ('root_canal', 'Tratamiento de Conducto'), ('bridge', 'Puente'), ('veneer', 'Carilla'), ('mobility', 'Movilidad'), ('fracture', 'Fractura'), ('impacted', 'Impactado'), ('other', 'Otro')], max_length=15, verbose_name='Tipo de Condición')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('diagnosis_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Diagnóstico')),
                ('condition_state', models.CharField(choices=[('active', 'Activa'), ('treated', 'Tratada'), ('in_treatment', 'En Tratamiento'), ('under_observation', 'En Observación')], default='active', max_length=20, verbose_name='Estado de la condición')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosed_conditions', to=settings.AUTH_USER_MODEL, verbose_name='Dentista')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tooth_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='registros_dentales.toothstatus', verbose_name='Estado del Diente')),
                ('surface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='registros_dentales.toothsurface', verbose_name='Superficie')),
            ],
            options={
                'verbose_name': 'Condición Dental',
                'verbose_name_plural': 'Condiciones Dentales',
                'db_table': 'dental_condition',
            },
        ),
        migrations.CreateModel(
            name='ToothTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('specific_description', models.TextField(verbose_name='Descripción Específica')),
                ('performed_date', models.DateField(verbose_name='Fecha de Realización')),
                ('treatment_state', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='completed', max_length=15, verbose_name='Estado del tratamiento')),
                ('specific_materials', models.TextField(blank=True, verbose_name='Materiales Específicos Utilizados')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dental_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='registros_dentales.dentalcondition', verbose_name='Condición Tratada')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tooth_treatments', to=settings.AUTH_USER_MODEL, verbose_name='Dentista')),
                ('surface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='registros_dentales.toothsurface', verbose_name='Superficie')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='registros_dentales.tooth', verbose_name='Diente')),
                ('treatment_performed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_treatments', to='tratamientos.treatmentperformed', verbose_name='Tratamiento Realizado')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tratamiento por Diente',
                'verbose_name_plural': 'Tratamientos por Diente',
                'db_table': 'dental_tooth_treatment',
            },
        ),
    ]
