# Generated by Django 5.2.4 on 2025-07-04 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('paciente', '0002_pacientemodel_edad_and_more'),
        ('tratamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoPacienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Eliminado Lógicamente')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio del Tratamiento')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin del Tratamiento')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado del Tratamiento')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos', to='doctor.doctormodel', verbose_name='Doctor Asignado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos', to='paciente.pacientemodel', verbose_name='Paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='tratamiento.tratamientomodel', verbose_name='Tratamiento')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_actualizacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_creacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tratamiento del Paciente',
                'verbose_name_plural': 'Tratamientos de los Pacientes',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
