# Generated by Django 5.2.4 on 2025-07-04 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleteraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Eliminado Lógicamente')),
                ('nombre', models.CharField(help_text='Nombre que agrupa a formas de pago', max_length=30, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la billetera', null=True, verbose_name='Descripción')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_actualizacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_creacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
            },
        ),
        migrations.CreateModel(
            name='FormaPagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Eliminado Lógicamente')),
                ('nombre', models.CharField(help_text='Nombre de la forma de pago', max_length=30, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la forma de pago', null=True, verbose_name='Descripción')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total en la forma de pago')),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='pago.billeteramodel', verbose_name='Billetera')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_actualizacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_creacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='TransaccionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Eliminado Lógicamente')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Transacción')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la transacción', null=True, verbose_name='Descripción')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Transacción')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], default='ingreso', max_length=20, verbose_name='Tipo de Transacción')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='pago.formapagomodel', verbose_name='Forma de Pago')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_actualizacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_creacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
