# Generated by Django 5.2.4 on 2025-07-04 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagomodel',
            name='billetera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formas_pago', to='pago.billeteramodel', verbose_name='Billetera'),
        ),
        migrations.AlterField(
            model_name='transaccionmodel',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='pago.formapagomodel', verbose_name='Forma de Pago'),
        ),
    ]
