# Generated by Django 5.2.4 on 2025-07-04 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanciamientoConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Eliminado Lógicamente')),
                ('nombre', models.CharField(help_text='Nombre del financiamiento', max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del financiamiento', null=True, verbose_name='Descripción')),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Interés (%)')),
                ('plazo_meses', models.PositiveIntegerField(default=12, verbose_name='Plazo (meses)')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_actualizacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_creacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Financiamiento',
                'verbose_name_plural': 'Configuraciones de Financiamiento',
            },
        ),
    ]
