# Generated by Django 5.2.5 on 2025-08-31 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_usermodel_address_alter_usermodel_date_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeethModel',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.auditmodel')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('type_temp', models.CharField(choices=[('1', 'Permanente'), ('2', 'Temporal')], max_length=1, verbose_name='Tipo de diente')),
            ],
            bases=('core.auditmodel',),
        ),
    ]
