# Generated by Django 5.2.5 on 2025-08-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teethmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teeth/', verbose_name='Imagen'),
        ),
    ]
