# Generated by Django 5.2.5 on 2025-08-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontogram', '0002_teethmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teethmodel',
            name='type_temp',
            field=models.CharField(blank=True, choices=[('1', 'Permanente'), ('2', 'Temporal')], max_length=1, null=True, verbose_name='Tipo de diente'),
        ),
    ]
