# Generated by Django 5.2.5 on 2025-09-01 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_usermodel_address_alter_usermodel_date_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresRateModel',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.auditmodel')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('core.auditmodel',),
        ),
    ]
