# Generated by Django 5.2.5 on 2025-09-01 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usermodel_address_alter_usermodel_date_birth_and_more'),
        ('financing', '0001_initial'),
        ('treatments', '0004_alter_appliedtreatmentsmodel_apply_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingModel',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.auditmodel')),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Enganche')),
                ('total_financed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Financiado')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago Mensual')),
                ('interest_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financing.interesratemodel', verbose_name='Tasa de Interés')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financings', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatments.appliedtreatmentsmodel', verbose_name='Tratamiento')),
            ],
            bases=('core.auditmodel',),
        ),
        migrations.CreateModel(
            name='PaymentsModel',
            fields=[
                ('auditmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.auditmodel')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('financing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financing.financingmodel')),
            ],
            bases=('core.auditmodel',),
        ),
    ]
