# Generated by Django 5.2.5 on 2025-09-01 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0002_financingmodel_paymentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingmodel',
            name='date_payment',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='financing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financing.financingmodel', verbose_name='Financiamiento'),
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='payment_date',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
    ]
