# Generated by Django 5.2.4 on 2025-07-04 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Eliminado Lógicamente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Paciente')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno del Paciente')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno del Paciente')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=10, verbose_name='Género')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('calle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Exterior')),
                ('colonia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia')),
                ('cp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('enfermedades', models.TextField(blank=True, null=True, verbose_name='Enfermedades Preexistentes')),
                ('antecedentes_familiares', models.TextField(blank=True, null=True, verbose_name='Antecedentes Familiares')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_actualizacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_auditoria_creacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
                'unique_together': {('nombre', 'apellido_paterno', 'apellido_materno', 'fecha_nacimiento')},
            },
        ),
    ]
