# Generated by Django 5.2.4 on 2025-07-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientemodel',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad en años', null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='pacientemodel',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Formato: YYYY-MM-DD', null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
