# Generated by Django 5.2.5 on 2025-08-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='type_user',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('secretary', 'Secretaria'), ('patient', 'Paciente'), ('assistant', 'Asistente')], default='patient', max_length=20, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
